// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2wPDJtfwkV6KVPX110_YT2C6gZ3E9vBM',
    appId: '1:514083905488:web:9684167d3860a08d2ea3d5',
    messagingSenderId: '514083905488',
    projectId: 'graphic-jet-324619',
    authDomain: 'graphic-jet-324619.firebaseapp.com',
    storageBucket: 'graphic-jet-324619.firebasestorage.app',
    measurementId: 'G-SM6GFXDB3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbmZPdGQlkZJPxN-Ydfb3yMvBpvCMvaao',
    appId: '1:514083905488:android:0633c5acd68ebad82ea3d5',
    messagingSenderId: '514083905488',
    projectId: 'graphic-jet-324619',
    storageBucket: 'graphic-jet-324619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATm-4dI56pJeTmTVkbWHuolFF7Qcm_StE',
    appId: '1:514083905488:ios:32d28b3a461b56de2ea3d5',
    messagingSenderId: '514083905488',
    projectId: 'graphic-jet-324619',
    storageBucket: 'graphic-jet-324619.firebasestorage.app',
    iosBundleId: 'com.example.registrationForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATm-4dI56pJeTmTVkbWHuolFF7Qcm_StE',
    appId: '1:514083905488:ios:32d28b3a461b56de2ea3d5',
    messagingSenderId: '514083905488',
    projectId: 'graphic-jet-324619',
    storageBucket: 'graphic-jet-324619.firebasestorage.app',
    iosBundleId: 'com.example.registrationForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2wPDJtfwkV6KVPX110_YT2C6gZ3E9vBM',
    appId: '1:514083905488:web:53f8226931c080252ea3d5',
    messagingSenderId: '514083905488',
    projectId: 'graphic-jet-324619',
    authDomain: 'graphic-jet-324619.firebaseapp.com',
    storageBucket: 'graphic-jet-324619.firebasestorage.app',
    measurementId: 'G-3F13RRD0D1',
  );

}